import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const AboutPage: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Tie & Dye Zone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p>AboutPage Page</p>
        </div>
    )
}

export default AboutPage
